universe = vanilla
log    =    log/proj-chtc_$(Cluster)_$(Process).log
error  =  error/proj-chtc_$(Cluster)_$(Process).err
output = output/proj-chtc_$(Cluster)_$(Process).out

executable = ./test.sh

arguments = $(filename)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = test7/$(filename), test.py, test.sh, http://proxy.chtc.wisc.edu/SQUID/chtc/el8/python310.tar.gz, packages.tar.gz

transfer_output_files = $(filename).csv

request_cpus = 1
request_memory = 500MB
request_disk = 510MB

queue filename from test.txt